//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class books_table
    {
        public int C_book_id { get; set; }
        public string C_title { get; set; }
        public string C_author { get; set; }
        public string C_year { get; set; }
        public string C_genre { get; set; }
        public string C_available { get; set; }
        public string C_date_of_issue { get; set; }
        public Nullable<int> C_user_id { get; set; }
    
        public virtual users_table users_table { get; set; }
    }
}
